/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){CKEDITOR.plugins.add("uploadwidget",{lang:"az,ca,cs,da,de,de-ch,el,en,en-au,eo,es,es-mx,eu,fr,gl,hr,hu,id,it,ja,km,ko,ku,nb,nl,no,oc,pl,pt,pt-br,ro,ru,sk,sv,tr,ug,uk,zh,zh-cn",requires:"widget,clipboard,filetools,notificationaggregator",init:function(a){a.filter.allow("*[!data-widget,!data-cke-upload-id]")}});CKEDITOR.fileTools||(CKEDITOR.fileTools={});CKEDITOR.tools.extend(CKEDITOR.fileTools,{addUploadWidget:function(a,b,e){var k=CKEDITOR.fileTools,c=a.uploadRepository,m=e.supportedTypes?
10:20;if(e.fileToElement)a.on("paste",function(f){f=f.data;var l=a.widgets.registered[b],g=f.dataTransfer,e=g.getFilesCount(),h=l.loadMethod||"loadAndUpload",d,n;if(!f.dataValue&&e)for(n=0;n<e;n++)if(d=g.getFile(n),!l.supportedTypes||k.isTypeSupported(d,l.supportedTypes)){var m=l.fileToElement(d);d=c.create(d);m&&(d[h](l.uploadUrl,l.additionalRequestParameters),CKEDITOR.fileTools.markElement(m,b,d.id),"loadAndUpload"!=h&&"upload"!=h||l.skipNotifications||CKEDITOR.fileTools.bindNotifications(a,d),
f.dataValue+=m.getOuterHtml())}},null,null,m);CKEDITOR.tools.extend(e,{downcast:function(){return new CKEDITOR.htmlParser.text("")},init:function(){var f=this,b=this.wrapper.findOne("[data-cke-upload-id]").data("cke-upload-id"),g=c.loaders[b],e=CKEDITOR.tools.capitalize,h,d;g.on("update",function(c){if(f.wrapper&&f.wrapper.getParent()){a.fire("lockSnapshot");c="on"+e(g.status);if("function"!==typeof f[c]||!1!==f[c](g))d="cke_upload_"+g.status,f.wrapper&&d!=h&&(h&&f.wrapper.removeClass(h),f.wrapper.addClass(d),
h=d),"error"!=g.status&&"abort"!=g.status||a.widgets.del(f);a.fire("unlockSnapshot")}else a.editable().find('[data-cke-upload-id\x3d"'+b+'"]').count()||g.abort(),c.removeListener()});g.update()},replaceWith:function(b,c){if(""===b.trim())a.widgets.del(this);else{var g=this==a.widgets.focused,e=a.editable(),h=a.createRange(),d,k;g||(k=a.getSelection().createBookmarks());h.setStartBefore(this.wrapper);h.setEndAfter(this.wrapper);g&&(d=h.createBookmark());e.insertHtmlIntoRange(b,h,c);a.widgets.checkWidgets({initOnlyNew:!0});
a.widgets.destroy(this,!0);g?(h.moveToBookmark(d),h.select()):a.getSelection().selectBookmarks(k)}}});a.widgets.add(b,e)},markElement:function(a,b,e){a.setAttributes({"data-cke-upload-id":e,"data-widget":b})},bindNotifications:function(a,b){function e(){k=a._.uploadWidgetNotificaionAggregator;if(!k||k.isFinished())k=a._.uploadWidgetNotificaionAggregator=new CKEDITOR.plugins.notificationAggregator(a,a.lang.uploadwidget.uploadMany,a.lang.uploadwidget.uploadOne),k.once("finished",function(){var b=k.getTaskCount();
0===b?k.notification.hide():k.notification.update({message:1==b?a.lang.uploadwidget.doneOne:a.lang.uploadwidget.doneMany.replace("%1",b),type:"success",important:1})})}var k,c=null;b.on("update",function(){!c&&b.uploadTotal&&(e(),c=k.createTask({weight:b.uploadTotal}));c&&"uploading"==b.status&&c.update(b.uploaded)});b.on("uploaded",function(){c&&c.done()});b.on("error",function(){c&&c.cancel();a.showNotification(b.message,"warning")});b.on("abort",function(){c&&c.cancel();a.showNotification(a.lang.uploadwidget.abort,
"info")})}})})();